In [8]:
import pandas as pd
import numpy as np
import joblib

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

In [9]:
X_train = pd.read_csv("../datasets/X_train.csv")
X_test = pd.read_csv("../datasets/X_test.csv")

y_train = pd.read_csv("../datasets/y_train.csv").values.ravel()
y_test = pd.read_csv("../datasets/y_test.csv").values.ravel()

print("Training Data:", X_train.shape)
print("Testing Data :", X_test.shape)

Training Data: (491, 11)
Testing Data : (123, 11)

In [10]:
models = {
    "Decision Tree": DecisionTreeClassifier(random_state=42),

    "Random Forest": RandomForestClassifier(
        n_estimators=100,
        random_state=42
    ),

    "KNN": KNeighborsClassifier(
        n_neighbors=5
    ),

    "XGBoost": XGBClassifier(
        random_state=42,
        eval_metric="logloss"
    )
}

In [11]:
results = []

best_model = None
best_accuracy = 0

for name, model in models.items():

    print("="*50)
    print(name)

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    train_acc = accuracy_score(
        y_train,
        model.predict(X_train)
    )

    test_acc = accuracy_score(
        y_test,
        y_pred
    )

    precision = precision_score(
        y_test,
        y_pred
    )

    recall = recall_score(
        y_test,
        y_pred
    )

    f1 = f1_score(
        y_test,
        y_pred
    )

    results.append([
        name,
        train_acc,
        test_acc,
        precision,
        recall,
        f1
    ])

    print("Train Accuracy :", round(train_acc,4))
    print("Test Accuracy  :", round(test_acc,4))

    if test_acc > best_accuracy:
        best_accuracy = test_acc
        best_model = model

==================================================
Decision Tree
Train Accuracy : 1.0
Test Accuracy  : 0.7642
==================================================
Random Forest
Train Accuracy : 1.0
Test Accuracy  : 0.8293
==================================================
KNN
Train Accuracy : 0.8167
Test Accuracy  : 0.8455
==================================================
XGBoost
Train Accuracy : 1.0
Test Accuracy  : 0.813

In [12]:
comparison = pd.DataFrame(
    results,
    columns=[
        "Model",
        "Training Accuracy",
        "Testing Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ]
)

comparison

,Model,Training Accuracy,Testing Accuracy,Precision,Recall,F1 Score
0,Decision Tree,1.000000,0.764228,0.825581,0.835294,0.830409
1,Random Forest,1.000000,0.829268,0.847826,0.917647,0.881356
2,KNN,0.816701,0.845528,0.836735,0.964706,0.896175
3,XGBoost,1.000000,0.813008,0.852273,0.882353,0.867052

In [13]:
comparison = comparison.sort_values(
    by="Testing Accuracy",
    ascending=False
)

comparison

,Model,Training Accuracy,Testing Accuracy,Precision,Recall,F1 Score
2,KNN,0.816701,0.845528,0.836735,0.964706,0.896175
1,Random Forest,1.000000,0.829268,0.847826,0.917647,0.881356
3,XGBoost,1.000000,0.813008,0.852273,0.882353,0.867052
0,Decision Tree,1.000000,0.764228,0.825581,0.835294,0.830409

In [14]:
comparison.to_csv(
    "../models/model_comparison.csv",
    index=False
)

print("Comparison Saved")

Comparison Saved

In [15]:
joblib.dump(
    best_model,
    "../models/smart_lender_model.pkl"
)

print("Best Model Saved Successfully")

Best Model Saved Successfully

In [16]:
print(comparison)

print("\nBest Model")

print(comparison.iloc[0])

           Model  Training Accuracy  Testing Accuracy  Precision    Recall  \
2            KNN           0.816701          0.845528   0.836735  0.964706
1  Random Forest           1.000000          0.829268   0.847826  0.917647
3        XGBoost           1.000000          0.813008   0.852273  0.882353
0  Decision Tree           1.000000          0.764228   0.825581  0.835294

   F1 Score
2  0.896175
1  0.881356
3  0.867052
0  0.830409

Best Model
Model                     KNN
Training Accuracy    0.816701
Testing Accuracy     0.845528
Precision            0.836735
Recall               0.964706
F1 Score             0.896175
Name: 2, dtype: object